### ISSUE TITLE
deferred rendering on inactive browser tabs (with jQuery-1.6.2)

### ISSUE THREAD

**Issue by ghost** [wesbaker/jquery.innerFade#10]
When an innerFade loop is running on an inactive browser tab, jQuery keeps on planning fades, but renders all fades planned when focus comes back to the tab. Even though I think that in essence this is a jQuery bug (or feature), i was forced to work with jQuery 1.6.2 so I patched jquery.innerFade instead. 

The patch doesn't stop the timers, instead it just resets the timers with the same values every time it's called and the window is not active.

In case anyone needs it, the patch can be found here: http://intellibiz.org/jqif/jquery.innerFade-window.isActive.patch

**Comment by wesbaker** [comment]
@intellibiz, this looks like a nice patch. Any chance you could fork the repository and do a [Pull Request](http://help.github.com/send-pull-requests/)?

**Comment by ghost** [comment]
Can do, expect it somewhere tomorrow.
