### ISSUE TITLE
Random / Random start display all images at once

### ISSUE THREAD

**Issue by VIII** [wesbaker/jquery.innerFade#16]
Hey, a bug I have found is that random and random start (in experimental) display all slides at once. The gradually clear out as it cycles through, but I have not been able to solve this. Any ideas?

**Comment by wesbaker** [comment]
No, I haven't seen that since I don't use random. It will be a while before I can look at it (maybe July). You might take a look at jQuery Cycle to see if that works for you.

**Comment by olance** [comment]
Hi,
I'm having the exact same issue and have _-snip-(fixed it)-snip-_ started to fix it. Will send a pull request!

**Comment by olance** [comment]
I've sent a [pull request](https://github.com/wesbaker/jquery.innerFade/pull/17) — I'm not sure it's the same issue though @VIII, I'll let you check :)

**Comment by wesbaker** [comment]
Should be fixed by wesbaker/jquery.innerFade#17, though I haven't had the chance to check.
