### ISSUE TITLE
Bugging out in IE7/IE8

### ISSUE THREAD

**Issue by sarmo** [wesbaker/jquery.innerFade#19]
Hi,

I have a rotating slider on a WordPress site using this, and it works in all browsers except IE7 and IE8.
All my slides are visible at once, below each other, and the scrolling links do not work.

I am using jQuery v1.10. All I can find are people with kind of similar problems but not the same as mine, it's not a conflicting plugin, as I have removed everything else (masonry.js and imagesloaded.js) and it still was giving issues.

Any ideas or help will be much appreciated!

Thanks.

**Comment by sarmo** [comment]
So, I have found the error and where it is coming from, but not sure how to fix this:
'elements' is null or not an object (jquery.innerfade.js line 135)

Anyone?

**Comment by wesbaker** [comment]
Did you close this issue because you figured it out or are you just giving up on it?
