### ISSUE TITLE
Add Indexes

### ISSUE THREAD

**Issue by wesbaker** [wesbaker/jquery.innerFade#2]
Indexes would be representations of the various slides in the container. Clicking them would take you to the that slide.

**Comment by kevincupp** [comment]
That's for implementing this, Wes. Could you also have the plugin add a "selected" class to whichever list item the current index corresponds to?

**Comment by wesbaker** [comment]
Sure I'll put it in the next version.

**Comment by wesbaker** [comment]
The indexes are implemented and the selected class is 'active'.
